workflows:
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        environment:
            groups:
                - appstore_credentials
                # Add the above mentioned group environment variables in Codemagic UI (either in Application/Team variables): 
                #APP_STORE_CONNECT_ISSUER_ID: "dc9f16f7-3977-4135-9fbf-3e7e645d904f",
                #APP_STORE_CONNECT_KEY_IDENTIFIER: "5GYRAZ9XYH",
                #
                #CERTIFICATE_PRIVATE_KEY
            vars:
                XCODE_WORKSPACE: "ios/Test.xcworkspace" # <-- Put the name of your Xcode workspace here
                XCODE_SCHEME: "Test" # <-- Put the name of your Xcode scheme here
                BUNDLE_ID: "com.squashn"
            node: v16.11.1
            xcode: 13
            cocoapods: default
        scripts:
            - name: Install python crypto
              script: python3 -m pip install --upgrade pyjwt[crypto]
            - name: Install npm dependencies
              script: |
                npm install
            - name: Install pod dependencies
              script: |
                 cd ios && pod install
                 
            - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
              script: keychain initialize
            - name: Fetch signing files
              script: |
                  # You can allow creating resources if existing are not found with `--create` flag
                  app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT --create     
                  
            - name: Set up signing certificate
              script: keychain add-certificates
              
            - name: Set up code signing settings on Xcode project
              script: xcode-project use-profiles
         
            - name: Run project
              script: |
                #npx react-native run-ios --configuration=release
                xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
            
        artifacts:
            #- $HOME/Test.ipa
            - build/ios/ipa/*.ipa
            #- $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
            #- $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphonesimulator/Squash.n.app
